# Array Creation : Conversion From Other Python Structures

Conversion from other Python structures (i.e. lists and tuples)

Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

Replicating, joining, or mutating existing arrays

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions (e.g., random)

In [1]:
import numpy as np

In [2]:
listarray =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
listarray.dtype

dtype('int64')

In [5]:
listarray.size

9

In [6]:
listarray.shape

(3, 3)

In [7]:
np.array({53,54,54})

array({53, 54}, dtype=object)

In [8]:
zeros=np.zeros((3,6))

In [9]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
zeros.shape

(3, 6)

In [11]:
arr = np.arange(10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
lnspc=np.linspace(1,6,5)

In [14]:
lnspc

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [17]:
emp=np.empty((5,8))

In [18]:
emp

array([[ 1.14949689e-316,  4.77830973e-299, -8.73989998e+245,
         1.31390969e-311,  5.56268866e-308,  5.56735443e+096,
         5.54150810e+257,  2.65818575e-309],
       [-3.32653202e-111,  1.10825055e-301,  1.11067912e-310,
         1.31390969e-311,  8.73990775e+245,  1.30951421e-251,
        -1.73955385e+078,  7.54792551e+168],
       [ 4.94065646e-324,  6.36598737e-314,  1.31390969e-311,
         3.31916099e-309,  4.94343124e-310,  9.94646473e+086,
         9.88131292e-324,  0.00000000e+000],
       [ 2.13142979e-053,  2.75164205e-135,  1.31390969e-311,
         1.17123382e+166,  7.80704798e-271,  1.14448870e+243,
         7.87260438e-312,  1.33360299e+241],
       [ 4.64165359e-310,  1.31390969e-311, -2.11881741e-226,
         1.21185633e-093,  4.22259016e+239,  9.75115950e-196,
         3.28446469e+111,  8.20665349e+006]])

In [22]:
emp_like=np.empty_like(lnspc)

In [23]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 1.39612477e-309, 7.74860419e-304,
       7.74860419e-304])

In [19]:
idn=np.identity(20)

In [20]:
idn

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [21]:
idn.shape

(20, 20)

In [24]:
array=np.arange(99)

In [25]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
array.reshape(3,30)

ValueError: cannot reshape array of size 99 into shape (3,30)

In [29]:
array=array.reshape(3,33)

In [30]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
array=array.ravel()

In [34]:
array.shape

(99,)