# Matrix Operations 

In [1]:
import numpy as np

In [2]:
arr1=np.array([[1, 6, 2],
       [4, 24, 9],
       [6, 3, 78]])

In [3]:
arr1

array([[ 1,  6,  2],
       [ 4, 24,  9],
       [ 6,  3, 78]])

In [4]:
arr2=np.array([[1, 4, 3],
       [4, 6, 3],
       [6, 3, 8]])

In [5]:
arr1+arr2

array([[ 2, 10,  5],
       [ 8, 30, 12],
       [12,  6, 86]])

In [6]:
arr1*arr2

array([[  1,  24,   6],
       [ 16, 144,  27],
       [ 36,   9, 624]])

In [7]:
arr1-arr2

array([[ 0,  2, -1],
       [ 0, 18,  6],
       [ 0,  0, 70]])

In [8]:
np.sqrt(arr1)

array([[1.        , 2.44948974, 1.41421356],
       [2.        , 4.89897949, 3.        ],
       [2.44948974, 1.73205081, 8.83176087]])

In [9]:
arr1.sum()

np.int64(133)

In [10]:
arr1.max()

np.int64(78)

In [11]:
arr1.min()

np.int64(1)

In [12]:
arr1

array([[ 1,  6,  2],
       [ 4, 24,  9],
       [ 6,  3, 78]])

In [13]:
np.where(arr1>6)

(array([1, 1, 2]), array([1, 2, 2]))

In [14]:
arr1.dtype

dtype('int64')

In [15]:
type(np.where(arr1>6))

tuple

In [16]:
np.count_nonzero(arr1)

9

In [17]:
import sys

In [18]:
py_arr=[23,46,78,12]

In [19]:
np_arr = np.array(py_arr)

In [20]:
sys.getsizeof(1)*len(py_arr)

112

In [21]:
np_arr.itemsize*np_arr.size

32

In [ ]:
np.to