# NumPy Axis

In [1]:
import numpy as np

In [3]:
x = [[1,4,3],[4,6,3],[6,3,8]]

In [4]:
arr=np.array(x)

In [7]:
arr

array([[1, 4, 3],
       [4, 6, 3],
       [6, 3, 8]])

In [9]:
arr.sum(axis=0)

array([11, 13, 14])

In [10]:
arr.sum(axis=1)

array([ 8, 13, 17])

In [11]:
arr.T

array([[1, 4, 6],
       [4, 6, 3],
       [3, 3, 8]])

In [12]:
arr.flat

In [14]:
for i in arr.flat:
    print(i)

1
4
3
4
6
3
6
3
8


In [16]:
arr.ndim

2

In [17]:
arr.size

9

In [18]:
arr.nbytes

72

In [19]:
arr.max()

np.int64(8)

In [20]:
arr.min()

np.int64(1)

In [22]:
one=np.array([57,5,6,8,3,33])

In [23]:
one.argmax()

np.int64(0)

In [24]:
one.argmin()

np.int64(4)

In [25]:
one.argsort()

array([4, 1, 2, 3, 5, 0])

In [26]:
arr

array([[1, 4, 3],
       [4, 6, 3],
       [6, 3, 8]])

In [27]:
arr.argmax()

np.int64(8)

In [28]:
arr.argmin()

np.int64(0)

In [29]:
arr.argmax(axis=0)

array([2, 1, 2])

In [30]:
arr.argmax(axis=1)

array([1, 1, 2])

In [31]:
arr.argmin(axis=0)

array([0, 2, 0])

In [32]:
arr.argmin(1)

array([0, 2, 1])

In [33]:
arr.argsort(axis=0)

array([[0, 2, 0],
       [1, 0, 1],
       [2, 1, 2]])

In [34]:
arr.argsort(axis=1)

array([[0, 2, 1],
       [2, 0, 1],
       [1, 0, 2]])

In [36]:
arr.ravel()

array([1, 4, 3, 4, 6, 3, 6, 3, 8])

In [37]:
arr.reshape((6,1))

ValueError: cannot reshape array of size 9 into shape (6,1)